tap 'caskroom/cask'
tap 'caskroom/fonts'
tap 'homebrew/bundle'
tap 'homebrew/core'
tap 'homebrew/services'
cask 'java'
brew 'awscli'
brew 'fortune'
brew 'graphviz'
brew 'htop'
brew 'iperf3'
brew 'jenkins', restart_service: true
brew 'mas'
brew 'node'
brew 'packer'
brew 'pass'
brew 'sqlite'
brew 'python3'
brew 'ponysay'
brew 'python'
brew 'wallpaper'
brew 'wget'
brew 'zsh'
brew 'zsh-completions'
cask 'aerial'
cask 'alfred'
cask 'appcleaner'
cask 'atom'
cask 'bettertouchtool'
cask 'caffeine'
cask 'cord'
cask 'cyberduck'
cask 'dropbox'
cask 'flash-player'
cask 'font-source-code-pro'
cask 'google-drive'
cask 'iterm2'
cask 'joinme'
cask 'keyboardcleantool'
cask 'royal-tsx'
cask 'sourcetree'
cask 'teamviewer'
cask 'textmate'
cask 'textwrangler'
cask 'tunnelblick'
cask 'vagrant'
cask 'vagrant-manager'
cask 'virtualbox'
cask 'virtualbox-extension-pack'
cask 'vlc'
cask 'vnc-viewer'
mas 'Blackmagic Disk Speed Test', id: 425264550
mas 'iMovie', id: 408981434
mas 'Keynote', id: 409183694
mas 'Numbers', id: 409203825
mas 'Pages', id: 409201541
mas 'Space Gremlin', id: 414515628
mas 'Xcode', id: 497799835
